import type { MatchInfo, Team, ScoutAction, Lineup, SetResult, Player } from '@/types/volleyball';

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  const yyyy = d.getFullYear();
  return `${mm}/${dd}/${yyyy}`;
}

function formatTime(timeStr: string): string {
  return timeStr.replace(':', '.');
}

function generatePlayerLine(
  teamIndex: number,
  player: Player,
  playerIndex: number,
  lineup: Lineup,
  setCount: number,
  teamCode: string
): string {
  const positionsPerSet: string[] = [];
  // For simplicity, we use the initial lineup position for all sets
  const positions = [lineup.p1, lineup.p2, lineup.p3, lineup.p4, lineup.p5, lineup.p6];
  const posIdx = positions.indexOf(player.id);
  
  for (let s = 0; s < setCount; s++) {
    if (posIdx >= 0) {
      positionsPerSet.push(String(posIdx + 1));
    } else if (player.id === lineup.libero1 || player.id === lineup.libero2) {
      positionsPerSet.push('*');
    } else {
      positionsPerSet.push('');
    }
  }

  // Pad to 5 sets
  while (positionsPerSet.length < 5) positionsPerSet.push('');

  const liberoFlag = player.isLibero ? 'L' : '';
  const captainFlag = player.isCaptain ? 'C' : '';
  const teamPlayerCode = `${teamCode}${player.number}`;

  return `${teamIndex};${player.number};${playerIndex};${positionsPerSet.join(';')};;;${teamPlayerCode};${player.lastName};${player.firstName};;${captainFlag};${liberoFlag};${player.isLibero ? '1' : ''};False;;;`;
}

function generateScoutCode(action: ScoutAction): string {
  const teamPrefix = action.team === 'home' ? '*' : 'a';
  const playerNum = String(action.playerNumber).padStart(2, '0');
  const skill = action.skill;
  const skillType = action.skillType;
  const evaluation = action.evaluation;
  
  const startZone = action.startZone ? String(action.startZone) : '~';
  const endZone = action.endZone ? String(action.endZone) : '~';
  const attackCode = action.attackCode || '~~';

  let extended = `${attackCode}~${startZone}${endZone}`;
  if (extended === '~~~') extended = '~~~';

  return `${teamPrefix}${playerNum}${skill}${skillType}${evaluation}${extended}`;
}

export function generateDVW(
  matchInfo: MatchInfo,
  homeTeam: Team,
  awayTeam: Team,
  homeLineup: Lineup,
  awayLineup: Lineup,
  actions: ScoutAction[],
  setResults: SetResult[],
  homeSetsWon: number,
  awaySetsWon: number
): string {
  const lines: string[] = [];
  const now = new Date();
  const dateStr = formatDate(matchInfo.date);
  const timeStr = formatTime(matchInfo.time);

  // [3DATAVOLLEYSCOUT]
  lines.push('[3DATAVOLLEYSCOUT]');
  lines.push('FILEFORMAT: 2.0');
  lines.push(`GENERATOR-DAY: ${dateStr} ${timeStr}`);
  lines.push('GENERATOR-IDP: DVW');
  lines.push('GENERATOR-PRG: VolleyScout Pro');
  lines.push('GENERATOR-REL: Release 1.0.0');
  lines.push('GENERATOR-VER: Web');
  lines.push(`GENERATOR-NAM: ${matchInfo.scorer || 'Scout'}`);
  lines.push(`LASTCHANGE-DAY: ${formatDate(now.toISOString().split('T')[0])} ${now.toTimeString().slice(0, 5).replace(':', '.')}`);
  lines.push('LASTCHANGE-IDP: DVW');
  lines.push('LASTCHANGE-PRG: VolleyScout Pro');
  lines.push('LASTCHANGE-REL: Release 1.0.0');
  lines.push('LASTCHANGE-VER: Web');
  lines.push(`LASTCHANGE-NAM: ${matchInfo.scorer || 'Scout'}`);

  // [3MATCH]
  lines.push('[3MATCH]');
  lines.push(`${dateStr};;${matchInfo.season};${matchInfo.league};${matchInfo.phase};;;;1;1;${matchInfo.totalSets === 5 ? 'M' : 'F'};0;`);
  lines.push(`;;${matchInfo.venue ? '42029' : ''};;;;R;L;`);

  // [3TEAMS]
  lines.push('[3TEAMS]');
  lines.push(`${homeTeam.code};${homeTeam.name};3;${homeTeam.coach};${homeTeam.assistantCoach};16777215;`);
  lines.push(`${awayTeam.code};${awayTeam.name};0;${awayTeam.coach};${awayTeam.assistantCoach};16777215;`);

  // [3MORE]
  lines.push('[3MORE]');
  lines.push(`${matchInfo.referee1}, ${matchInfo.referee2};;;${matchInfo.venue};${matchInfo.city};${matchInfo.scorer};`);
  lines.push(`;${matchInfo.totalSets};10;`);

  // [3COMMENTS]
  lines.push('[3COMMENTS]');
  lines.push('Generated by VolleyScout Pro');

  // [3SET]
  lines.push('[3SET]');
  for (let i = 0; i < 5; i++) {
    if (i < setResults.length) {
      const sr = setResults[i];
      lines.push(`True;0-0;0-0;0-0;${sr.homeScore}-${sr.awayScore};${sr.homeScore + sr.awayScore};`);
    } else {
      lines.push('True;;;;;;');
    }
  }

  // [3PLAYERS-H]
  lines.push('[3PLAYERS-H]');
  homeTeam.players.forEach((player, idx) => {
    lines.push(generatePlayerLine(0, player, idx + 1, homeLineup, setResults.length || 1, homeTeam.code));
  });

  // [3PLAYERS-V]
  lines.push('[3PLAYERS-V]');
  awayTeam.players.forEach((player, idx) => {
    lines.push(generatePlayerLine(1, player, idx + 1, awayLineup, setResults.length || 1, awayTeam.code));
  });

  // [3ATTACKCOMBINATION]
  lines.push('[3ATTACKCOMBINATION]');
  // Standard attack combinations
  const defaultAttacks = [
    'X1;3;R;Q;Quick;;16711680;4956;C;;',
    'V5;4;R;H;High set in 4;;255;4912;F;;',
    'V6;2;L;H;High set in 2;;255;4988;B;;',
    'VP;8;C;H;High Pipe;;255;4150;P;1;',
    'PP;3;L;O;Setter tip;;16711680;4964;S;;',
    'V3;3;C;O;High set to 3;;255;4950;-;;',
  ];
  defaultAttacks.forEach(a => lines.push(a));

  // [3SETTERCALL]
  lines.push('[3SETTERCALL]');
  lines.push('K1;;Front Quick;;16711680;3949;4454;4958;;;');
  lines.push('K2;;Back Quick;;16711680;3864;4278;4974;;;');

  // [3WINNINGSYMBOLS]
  lines.push('[3WINNINGSYMBOLS]');
  lines.push('=~~~#~~~=~~~~~~~=/~~#~~~=/~~#~~~=~~~~~~~=~~~~~~~=~~~~~~~');

  // [3RESERVE]
  lines.push('[3RESERVE]');

  // [3SCOUT]
  lines.push('[3SCOUT]');

  // Initial lineup codes
  const homeLineupNums = actions.length > 0 ? actions[0].homeLineup : [];
  const awayLineupNums = actions.length > 0 ? actions[0].awayLineup : [];

  if (homeLineupNums.length === 6) {
    const setterPos = actions[0]?.homeSetterPosition || 1;
    lines.push(`*P${String(setterPos).padStart(2, '0')}>LUp;;;;;;;;1;${setterPos};${setterPos};;;;${homeLineupNums.join(';')};${awayLineupNums.join(';')};`);
  }
  if (awayLineupNums.length === 6) {
    const setterPos = actions[0]?.awaySetterPosition || 1;
    lines.push(`aP${String(setterPos).padStart(2, '0')}>LUp;;;;;;;;1;${setterPos};${setterPos};;;;${homeLineupNums.join(';')};${awayLineupNums.join(';')};`);
  }

  // Scout actions
  actions.forEach((action) => {
    const code = action.code || generateScoutCode(action);
    const timestamp = action.timestamp || '';
    const lineupStr = `${action.homeLineup.join(';')};${action.awayLineup.join(';')}`;
    lines.push(`${code};;;;;;;${timestamp};${action.setNumber};${action.homeSetterPosition};${action.awaySetterPosition};;;;${lineupStr};`);
  });

  // Point lines
  let lastPointHome = 0;
  let lastPointAway = 0;
  actions.forEach((action) => {
    if (action.homeScore !== lastPointHome || action.awayScore !== lastPointAway) {
      const team = action.homeScore > lastPointHome ? '*' : 'a';
      lines.push(`${team}p${String(action.homeScore).padStart(2, '0')}:${String(action.awayScore).padStart(2, '0')};;;;;;;${action.timestamp};${action.setNumber};${action.homeSetterPosition};${action.awaySetterPosition};;;;${action.homeLineup.join(';')};${action.awayLineup.join(';')};`);
      lastPointHome = action.homeScore;
      lastPointAway = action.awayScore;
    }
  });

  return lines.join('\n');
}
