// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-teams.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_teams_default = defineTool({
  name: "list_teams",
  title: "Elenca squadre",
  description: "Elenca le squadre visibili all'utente autenticato (rispetta le RLS della societ\xE0).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("teams").select("id, name, category, age_group, season, society_id").order("name", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { teams: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-athletes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_athletes_default = defineTool2({
  name: "list_athletes",
  title: "Elenca atlete",
  description: "Elenca le atlete accessibili all'utente. Filtro opzionale per team_id.",
  inputSchema: {
    team_id: z.string().uuid().optional().describe("UUID della squadra per filtrare le atlete.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato." }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("athletes").select("id, first_name, last_name, role, number, team_id, society_id").order("last_name", { ascending: true });
    if (team_id) q = q.eq("team_id", team_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { athletes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-matches.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_matches_default = defineTool3({
  name: "list_matches",
  title: "Elenca partite",
  description: "Elenca le partite scoutate accessibili all'utente, ordinate per data (pi\xF9 recenti prima).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Numero massimo di partite da restituire (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato." }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("matches").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ooqiqwlkmyzdiqvuvcqe";
var mcp_default = defineMcp({
  name: "volleyscout-mcp",
  title: "VolleyScout Pro",
  version: "0.1.0",
  instructions: "Strumenti per VolleyScout Pro: leggi squadre, atlete e partite della societ\xE0 dell'utente autenticato. Tutti i tool rispettano le RLS della piattaforma.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_teams_default, list_athletes_default, list_matches_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
